
# test
TEST = 1

#TODO
DOWNLOAD_DIR = '~/Downloads'
TARGET_DIR = '/home/nbonamy/src/download-manager/'

# status
STATUS_ERROR = -1
STATUS_CREATED = 0
STATUS_DOWNLOADING = 1
STATUS_COMPLETED = 2
STATUS_PROCESSED = 3
STATUS_CANCELLED = 9
