
# paths
DATABASE_PATH = '../data/downtobox.db'
CONFIG_PATH = '../config/downtobox.conf'

# status
STATUS_ERROR = -1
STATUS_CREATED = 0
STATUS_STARTING = 1
STATUS_DOWNLOADING = 2
STATUS_COMPLETED = 3
STATUS_PROCESSED = 4
STATUS_CANCELLED = 9

# progress
SPEED_CALC_TIME_RANGE = 30
